spring:
  datasource:
    name: order
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/order
  flyway:
    locations: [ "classpath:/flyway" ]
    out-of-order: true
server:
  port: 8888
